### PR TITLE
Add option to pass a function for rendering error handling

### PR DESCRIPTION
**Pull request by Menci**
Currently this library only print the rendering error message with `console.log`. This PR add a option `config.errorHandler` to let developers do something on error, such as show stylized error message on the page.

The current behavior is preserved via the default value of `config.errorHandler`.

### CODE REVIEW

**Comment by Menci** [comment]
Oh, sorry. I broke something.

**Comment by Menci** [comment]
@pkra ping

**Comment by pkra** [comment]
@Menci could you rebase and add a test?

**Comment by Menci** [comment]
Test added. Commits merged into one and force-pushed. Conflits resolved.

**Comment by pkra** [comment]
Awesome -- thanks so much!

**Pull request merged**
