### PR TITLE
Add passing input and result by jsdom object

### LINKED ISSUE #62: Use JSDOM document as input and output to avoid reserialization
This is similar to #7, but the fix in there doesn't cover my use case. I have a long chain of processing that passes around a JSDOM document. Before mathjax-node-page, I serialize to a string to pass it to JSDOM, then after, I parse the mathjax-node-page output to get a JSDOM document. This seems a bit silly considering mathjax-node-page is operating on a JSDOM document.

I want to be able to provide a complete JSDOM document as input, and receive a JSDOM document as output. Ideally, just modified in place for best performance.

### PR DESCRIPTION
**Pull request by Menci**
This PR enables developers to call `mjpage()` with a `jsdom` object, and receive result with the object itself -- no extra serialization/deserialization is required.

Notice that developers must use `JSDOM` class exported from this library, not installed by themselves. This is because different versions of JSDOM may cause compatibility issues and make it hard to check the argument's type.

When a `jsdom` object is passed to `mjpage()`, `configOptions.jsdom` will be ignored, `beforeSerialization` event won't be triggered, the `callback` will receive the passed `jsdom` object itself.

I've tested it in my project.

This will close #62.

### CODE REVIEW

**Comment by pkra** [comment]
Thanks for this. I'll try to find time to take a proper look.

**Comment by Menci** [comment]
@pkra ping

**Comment by pkra** [comment]
Thanks for the ping. I should get to this later this week.

**Comment by pkra** [comment]
@Menci sorry for the additional delay. This looks good to me. Could you add a test?

**Comment by Menci** [comment]
Maybe tomorrow (UTC+8) I'll do it.

**Comment by Menci** [comment]
@pkra ping

**Comment by pkra** [comment]
Thanks a lot, @Menci !

**Pull request merged**
