### PR TITLE
mjpage.js: fix typo in usage

### PR DESCRIPTION
**Pull request by ickc**

### CODE REVIEW

**Comment by pkra** [comment]
Thanks for the PR. The file is actually called that so I'm not sure what you are after.

**Comment by ickc** [comment]
If you install it through npm the name is just `mjpage`, not `mjpage.js`.

Alternatively, may be it can intelligently return the name called from the command line.

**Comment by pkra** [comment]
> If you install it through npm the name is just mjpage, not mjpage.js.

Ah! Thanks for pointing out the discrepancy between package.json and mjpage.js. I'll think about it.

**Comment by pkra** [comment]
I think it would be best to rename `mjpage.js` to `mjpage`. @ickc could you update the PR? Otherwise, I can make a fresh one.

**Comment by ickc** [comment]
I deleted the old fork so I forked it again and made the pull request at #23.

**Pull request closed without merging**
